### ISSUE TITLE
I sometimes use dictchannel.jl but this version does not work on 1.0 as AbstractChannel needs a type. 

### ISSUE THREAD

**Issue by zahachtah** [JuliaAttic/Examples#1]

**Comment by nalimilan** [comment]
Please be more specific.

**Comment by StefanKarpinski** [comment]
This is an old, unmaintained repo.

**Comment by zahachtah** [comment]
Sorry, I know its old, but useful when learning to use RemoteChannels. I would not be surprised if more found it by google searching. 

I don't have a very good grasp of how to write the type declarations. 

We have: 

```julia
mutable struct DictChannel <: AbstractChannel
    d::Dict
    cond_take::Condition    # waiting for data to become available
    DictChannel() = new(Dict(), Condition())
end
```
and I got it to work on 1.0 by using:

```julia
mutable struct DictChannel <: AbstractChannel{Any}
    d::Dict
    cond_take::Condition    # waiting for data to become available
    DictChannel() = new(Dict(), Condition())
end
```

but I assume there's a more specific and efficient parametric type to use but I didn't figure it out yet. I really need to sit down and learn the julia type system, just a user programmer here....

**Comment by StefanKarpinski** [comment]
That seems fine and is equivalent to what it used to do.
